name: build-hac2l-windows
on: [push, pull_request, workflow_dispatch]

jobs:
  win-msys2:
    runs-on: windows-latest
    steps:
      - name: Checkout hac2l
        uses: actions/checkout@v4

      # lấy đúng "libraries" từ monorepo Atmosphere
      - name: Checkout Atmosphere (libraries only)
        uses: actions/checkout@v4
        with:
          repository: Atmosphere-NX/Atmosphere
          path: atmosphere
          sparse-checkout: |
            libraries
          sparse-checkout-cone-mode: false

      - name: Setup MSYS2 (UCRT64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            git
            make
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-pkgconf
            mingw-w64-ucrt-x86_64-zlib
            mingw-w64-ucrt-x86_64-zstd
            mingw-w64-ucrt-x86_64-lz4

      - name: Verify templates
        shell: msys2 {0}
        run: |
          test -f atmosphere/libraries/config/templates/stratosphere.mk && echo "templates OK"

      # dò target hợp lệ rồi build
      - name: Build
        shell: msys2 {0}
        env:
          LIBRARIES: ${{ github.workspace }}/atmosphere/libraries
        run: |
          set -e
          echo "LIBRARIES=$LIBRARIES"
          # liệt kê target có trong Makefile
          make -pRrq -f Makefile : 2>/dev/null | \
            awk -v RS= -F: '/^[^.#%][^:]*:([^=]|$)/ {print $1}' | \
            sort -u > targets.txt
          echo "Targets:" && sed -n '1,120p' targets.txt
          # ưu tiên các tên khả dĩ
          CHOSEN=""
          for t in release all nx_release host_release; do
            grep -qx "$t" targets.txt && CHOSEN="$t" && break
          done
          if [ -z "$CHOSEN" ]; then
            echo "No known target found; try default 'make'"
            make -j"$(nproc)" LIBRARIES="$LIBRARIES"
          else
            echo "Building target: $CHOSEN"
            make -j"$(nproc)" "$CHOSEN" LIBRARIES="$LIBRARIES"
          fi

      - name: Locate output
        shell: msys2 {0}
        run: |
          set -e
          f="$(find . -type f \( -iname 'hac2l.exe' -o -name 'hac2l' \) | head -n 1 || true)"
          [ -n "$f" ] || { echo "hac2l binary not found"; exit 1; }
          cp "$f" hac2l.exe 2>/dev/null || { cp "$f" hac2l && mv hac2l hac2l.exe; }
          test -f hac2l.exe && ls -l hac2l.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hac2l-windows-x64
          path: hac2l.exe
