name: build-hac2l-windows
on: [push, pull_request, workflow_dispatch]

jobs:
  win-msys2:
    runs-on: windows-latest
    steps:
      - name: Checkout Atmosphere (libraries + tạo tools/)
        uses: actions/checkout@v4
        with:
          repository: Atmosphere-NX/Atmosphere
          path: atmosphere
          sparse-checkout: |
            libraries
            tools
          sparse-checkout-cone-mode: false

      - name: Checkout hac2l vào atmosphere/tools/hac2l
        uses: actions/checkout@v4
        with:
          repository: Atmosphere-NX/hac2l
          path: atmosphere/tools/hac2l

      - name: MSYS2 toolchain
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            git
            make
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-pkgconf
            mingw-w64-ucrt-x86_64-zlib
            mingw-w64-ucrt-x86_64-zstd
            mingw-w64-ucrt-x86_64-lz4

      - name: Build
        shell: msys2 {0}
        working-directory: atmosphere/tools/hac2l
        run: |
          make -j"$(nproc)" || make release || make host_release
          f="$(find . -type f \( -iname 'hac2l.exe' -o -name 'hac2l' \) | head -n 1)"
          [ -n "$f" ] || { echo "no binary"; exit 1; }
          cp "$f" "$GITHUB_WORKSPACE/hac2l.exe" 2>/dev/null || { cp "$f" "$GITHUB_WORKSPACE/hac2l" && mv "$GITHUB_WORKSPACE/hac2l" "$GITHUB_WORKSPACE/hac2l.exe"; }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hac2l-windows-x64
          path: hac2l.exe
