name: build-hac2l-windows
on: [push, pull_request, workflow_dispatch]

jobs:
  win-msys2:
    runs-on: windows-latest
    steps:
      - name: Checkout hac2l
        uses: actions/checkout@v4

      # Lấy đúng thư mục libraries từ monorepo Atmosphere
      - name: Checkout Atmosphere (libraries only)
        uses: actions/checkout@v4
        with:
          repository: Atmosphere-NX/Atmosphere
          path: atmosphere
          sparse-checkout: |
            libraries
          sparse-checkout-cone-mode: false

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            git
            make
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-pkgconf
            mingw-w64-ucrt-x86_64-zlib

      - name: Debug paths
        shell: msys2 {0}
        run: |
          test -f atmosphere/libraries/config/templates/stratosphere.mk && echo "templates OK"

      - name: Build generic_windows
        shell: msys2 {0}
        run: |
          make -j"$(nproc)" generic_windows LIBRARIES=./atmosphere/libraries

      - name: Ensure .exe name
        shell: bash
        run: |
          if [ ! -f hac2l.exe ] && [ -f hac2l ]; then mv hac2l hac2l.exe; fi
          test -f hac2l.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hac2l-windows-x64
          path: hac2l.exe
