name: build-hac2l-windows

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  windows-msys2:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            git
            make
            mingw-w64-ucrt-x86_64-toolchain

      - name: Build with make
        shell: msys2 {0}
        run: |
          make -j"$(nproc)"

      - name: Ensure .exe name
        shell: bash
        run: |
          if [ ! -f hac2l.exe ] && [ -f hac2l ]; then mv hac2l hac2l.exe; fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hac2l-windows-x64
          path: hac2l.exe
